export enum MainFilter {
  Dairy = "Dairy",
  RawDairy = "Raw Dairy",
  Beef = "Beef",
  Pork = "Pork",
  Poultry = "Poultry",
  Seafood = "Seafood",
  Eggs = "Eggs",
  Fruits = "Fruits",
  Veggies = "Veggies",
  Grains = "Grains",
  Nuts = "Nuts/Seeds",
  Sugars = "Sugars",
  Supplement = "Supplement",
  Liver = "Liver",
  Tea = "Tea",
  GrassFed = "GrassFed",
  Honey = "Honey",
}
